### ISSUE TITLE
libhttpseverywhere can't be found

### ISSUE THREAD

**Issue by Vistaus** [grindhold/libhttpseverywhere#12]
If I try compile an app, in this case Epiphany (GNOME Web) which now includes libhttpseverywhere support in its Git repo, it says that libhttpseveryhwere can't be found on the system even though I successfully compiled and installed it with meson and ninja. I also tried symlinking libhttpseverywhere from /usr/local/lib64 and /usr/local/share it to /usr/lib64 and /usr/share to no avail.

```
checking for HTTPSEVERYWHERE... no
configure: error: Package requirements (httpseverywhere-0.2 >= 0.2) were not met:

No package 'httpseverywhere-0.2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables HTTPSEVERYWHERE_CFLAGS
and HTTPSEVERYWHERE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
vistaus@vistaus-arch:~/Apps/epiphany$ 
```

```
vistaus@vistaus-arch:~/Apps/epiphany$ locate libhttpseverywhere
/usr/local/lib64/libhttpseverywhere-0.2.so
/usr/local/share/libhttpseverywhere
/usr/local/share/libhttpseverywhere/rulesets.json
vistaus@vistaus-arch:~/Apps/epiphany$ 
```

How to solve this?

**Comment by grindhold** [comment]
i'm not that firm with arch but maybe ```sudo ldconfig``` will help. if it does not i will try to investigate in the evening.

**Comment by Vistaus** [comment]
That didn't help :( In that case I'll wait for you or @sternenseemann to help out.

**Comment by sternenseemann** [comment]
I don't know how the build system of epiphany works but I suppose you have to set the search paths of it to include `/usr/local`, dunno.

**Comment by Profpatsch** [comment]
Have you tried the stuff the rather helpful error message told you? Setting `PKG_CONFIG_PATH`? Read `man pkg-config` and see what it can tell you? Alternatively tried if `HTTPSEVERYWHERE_LIBS` works?

**Comment by sternenseemann** [comment]
> if you installed software in a non-standard prefix.

I suppose pkg-config doesn't search in `/usr/local` and doesn't like symlinks?

**Comment by sternenseemann** [comment]
@Vistaus try using the updated AUR package and let me know wether it works now.

**Comment by Vistaus** [comment]
Maybe it doesn't like symlinks indeed. I'll try the AUR package now and let you know how it goes in a few! :smile_cat:

**Comment by Vistaus** [comment]
I can confirm that the AUR package is fixed and epiphany builds now as it's able to find libhttpseverywhere now. Which leads me to the next question: what's different in the PKGBUILD compared to normal compiling?

**Comment by sternenseemann** [comment]
It is a proper package that installs the files into the standard system directories.

**Comment by sternenseemann** [comment]
#13 is basically the same issue now. Pls close this one.

**Comment by Vistaus** [comment]
Done :smile:
