### ISSUE TITLE
Context.init() should have an async variant

### ISSUE THREAD

**Issue by mcatanzaro** [grindhold/libhttpseverywhere#21]
HTTPSEverywhere.init() is synchronous, but it takes a long time to complete. We should make it asynchronous.

Also, HTTPSEverywhere.rewrite() is asynchronous, but it only blocks if called before init() completes. This is currently impossible, because init() is synchronous, so it's pointless for rewrite() to be async until this issue is fixed.

**Comment by grindhold** [comment]
closed by #19

**Comment by mcatanzaro** [comment]
Well I didn't do this yet!

**Comment by grindhold** [comment]
implemented in c103f250
