### ISSUE TITLE
Meson error about arguments

### ISSUE THREAD

**Issue by Vistaus** [grindhold/libhttpseverywhere#9]
I'm trying to build on Arch Linux and I've installed all of the dependencies, but upon invoking meson it returns an error:

vistaus@vistaus-arch:~/Apps/libhttpseverywhere/build$ meson ..
The Meson build system
Version: 0.35.0
Source dir: /run/media/vistaus/MicroSD/Apps/libhttpseverywhere
Build dir: /run/media/vistaus/MicroSD/Apps/libhttpseverywhere/build
Build type: native build

Meson encountered an error:
Arguments must be strings.
vistaus@vistaus-arch:~/Apps/libhttpseverywhere/build$ 

How to solve this?

**Comment by grindhold** [comment]
I only have meson 0.34.0 and i cannot reproduce the problem. Even with a fresh clone from github. I'm baffled that meson did not supply a line number where it encountered the error.

**Comment by mcatanzaro** [comment]
I think we should ask the meson developers to add a line number to the error message. It's working fine for me too with 0.34.0, I guess 0.35.0 is stricter somewhere.

**Comment by Vistaus** [comment]
Thanks for the quick replies!

I now built meson from Git (using the AUR package) and now it did throw line number errors for a package I seemed to be missing. And it builds afterwards. So I'll close this issue.

**Comment by sternenseemann** [comment]
@Vistaus I am maintainer of the AUR Package, I still need to fix it.
